title: Jones Magloire @Joxit
google_analytics: UA-99119327-1
remote_theme: chrisrhymes/bulma-clean-theme
description: Software developer and DevOPS @ Jawg Maps
author: Jones Magloire
twitter:
  username: Joxit
url: http://joxit.dev

subtitle: Product 1 tagline here
description: This is a product description
layout: product
image: https://via.placeholder.com/640x480
price: £1.99 + VAT
features:
    - label: Great addition to any home
      icon: fa-location-arrow
    - label: Comes in a range of styles
      icon: fa-grin-stars
    - label: Available in multiple sizes
      icon: fa-fighter-jet
rating: 3